spring:
  application:
    name: stock-reader
  cloud:
    openfeign:
      client:
        config:
          finnhub-client:
            url: https://finnhub.io/api/v1/
  kafka:
    bootstrap-servers: macdaddy.local:29093
hobbyinvestor:
  tasks:
    stock-symbols:
      cron: "0 */3 * * * *"
    company-details:
      cron: "*/30 * * * * *"
  topic-names:
    companyProfileUpdateTopic: companyProfileUpdate
    companyFinancialsUpdateTopic: companyFinancialsUpdate
    companyNewsUpdateTopic: companyNewsUpdate