spring:
  application:
    name: stock-reader
  cloud:
    openfeign:
      client:
        config:
          finnhub-client:
            url: https://finnhub.io/api/v1/stock/
hobbyinvestor:
  tasks:
    stock-symbols:
      cron: "0 */3 * * * *"
    stock-symbols-financials:
      cron: "0 25 */17 * * *"